### PR TITLE
WIP - Autocomplete

### PR DESCRIPTION
**Pull request by stevenwu**

### CODE REVIEW

**Comment by stevenwu** [comment]
@Matt-Jensen did you use something to generate the gists in the docs?

**Comment by Matt-Jensen** [comment]
Afraid it's simple but tedious.  I've been pasting into gist.github.com and copying the resulting <table> with the Chrome web inspector.  The gist table html has all the correct structure for the documentation styles.  Don't get hung up on this if it's too time consuming.  Getting working examples in the dummy app is probably a better use of your time.

**Comment by stevenwu** [comment]
I think it's ready for you to take a look, thanks.

**Comment by Matt-Jensen** [comment]
Merged your PR into the 0.4 release.  Thanks for all your hard work!

**Pull request merged**
