### PR TITLE
[RFC] Allow to customize & add options to Autocomplete service

### PR DESCRIPTION
**Pull request by montoias**
- Allow to use options in Autocomplete
- Enable custom classes on the Autocomplete input
- Enable placeholder on autocomplete input

### CODE REVIEW

**Comment by Matt-Jensen** [comment]
Sorry about the long delay.  While you have definitely highlighted the most likely candidates (placeholder and classes) for this approach, my concern is that this approach is [kind of a black hole](https://guides.emberjs.com/v2.9.0/templates/input-helpers).  We may be able to come up with a more robust solution by having the g-autocomplete component extend the [TextField Component](http://emberjs.com/api/classes/Ember.TextField.html).  Thoughts?

**Comment by montoias** [comment]
In relation with the placeholder and classes, I completely agree that it could simply be an extend of TextField.

In relation with the options, i believe they still are necessary.

https://github.com/Matt-Jensen/ember-cli-g-maps/pull/57/files#diff-aca4ec5cc19c0fec950b9cfc1e46bcbeR41

**Comment by Matt-Jensen** [comment]
I've created a [new branch here](https://github.com/Matt-Jensen/ember-cli-g-maps/tree/NI/add-g-autocomplete-options) of the proposed changes.  I've extend g-autocomplete with the TextField Component added tests and docs.  All that's left is for you to apply the options as you have done in your current branch.

Had to do it this way due to the deletion of `app/styles/style.scss` in the PR branch breaking the dummy application.  You still deserve all credit for adding autocomplete options, so if you want to commit that to the above branch I can get this merged.

**Comment by Matt-Jensen** [comment]
Ping @montoias you want me to wrap this up?

**Comment by montoias** [comment]
Will do it now @Matt-Jensen

**Pull request closed without merging**
