### PR TITLE
Add missing google API params

### PR DESCRIPTION
**Pull request by sukima**
* ~~`sensor`~~
* `client`

### CODE REVIEW

**Comment by Matt-Jensen** [comment]
Thank you @sukima! I wouldn't let the failing tests concern you.  That's probably related to how I'm currently subbing some of the unit tests. I'll be correcting that today.

Before any of these commits get published I'll need to write some documentation as well. Will keep you posted.

**Comment by sukima** [comment]
@Matt-Jensen removed deprecated `sensor` parameter. You were correct. (I :heart: `git rebase`).

**Comment by sukima** [comment]
@Matt-Jensen where is the documentation. I can add it if you like, README? gh-pages?

**Comment by Matt-Jensen** [comment]
If you're up for it, it would be very appreciated!  I'm using [ember-cli-github-pages](https://github.com/poetic/ember-cli-github-pages) for the docs
To update the relevant docs for this release you should check out `tests/dummy/app/pods/setup` I believe.

I'll just have to envy your rebasing powers for the moment (;

**Pull request merged**
